RUN_NAME: 'freematch_cifar10_40'
OUTPUT_DIR: 'model_ckpt'
CONT_TRAIN: False
RESUME: 'logs/freematch_cifar10_40/model_ckpt/last_checkpoint.pth'
SEED: 0
LOG_DIR: 'logs'
USE_CUDA: True
USE_TB: True
TB_DIR: 'tensorboard_runs/cifar_10_40_run_0'
VALIDATE_ONLY: False

DATASET:
  PREPARE: False
  DIR: 'data_download'
  NAME: 'cifar10'
  NUM_LABELED: 40
  NUM_CLASSES: 10
  NUM_WORKERS: 8
  CONVERT_ONE_HOT: False
  IMG_SIZE: 32
  URATIO: 7
  TRAIN_BATCH_SIZE: 64
  TEST_BATCH_SIZE: 512
  CROP_RATIO: 0.875
  PIXEL_MEAN: [0.4913, 0.4823, 0.4466]
  PIXEL_STD: [0.2470, 0.2435, 0.2615]
  RANDAUG_N: 3

MODEL:
  NAME: 'wrn_28_2'
  PRETRAINED: False
  PRETRAINED_PATH: ''

OPTIMIZER:

  NAME: 'SGD'
  LR: 0.03
  MOMENTUM: 0.9
  NESTEROV: True
  WEIGHT_DECAY: 0.0005
  SKIP_BN: True

TRAINER:

  SAT_EMA: 0.999
  AMP_ENABLED: True
  NUM_WARMUP_ITERS: 0
  NUM_TRAIN_ITERS: 1048576 # 2^20
  NUM_EVAL_ITERS: 512
  NUM_LOG_ITERS: 64
  EMA_VAL: 0.999
  ULB_LOSS_RATIO: 1.0
  ENT_LOSS_RATIO: 0.05