from yacs.config import CfgNode as CN

CFG = CN()

CFG.OUTPUT_DIR = ''
CFG.RESUME = ''
CFG.LOG_DIR = './logs'
CFG.USE_CUDA = True

CFG.USE_TB = True
CFG.PLOT_CURVES = True

CFG.DATASET = CN()
CFG.DATASET.PREPARE = False
CFG.DATASET.DIR = './data_download'
CFG.DATASET.NAME = 'cifar10'
CFG.DATASET.NUM_LABELED = 40
CFG.DATASET.NUM_CLASSES = 10
CFG.DATASET.CONVERT_ONE_HOT = True
CFG.DATASET.IMG_SIZE = 32
CFG.DATASET.URATIO = 7
CFG.DATASET.BATCH_SIZE = 64
CFG.DATASET.CROP_RATIO = 0.875
CFG.DATASET.PIXEL_MEAN = [0.485, 0.456, 0.406]
CFG.DATASET.PIXEL_STD = [0.229, 0.224, 0.225]
CFG.DATASET.RANDAUG_N = 3
CFG.DATASET.RANDAUG_M = 5


