from yacs.config import CfgNode as CN

CFG = CN()

CFG.RUN_NAME = 'freematch_cifar10_40'
CFG.OUTPUT_DIR = './model_ckpt'
CFG.CONT_TRAIN = False
CFG.RESUME = ''
CFG.LOG_DIR = './logs'
CFG.USE_CUDA = True

CFG.USE_TB = True
CFG.TB_FILENAME = 'tensorboard'
CFG.PLOT_CURVES = True

CFG.DATASET = CN()
CFG.DATASET.PREPARE = True
CFG.DATASET.DIR = './data_download'
CFG.DATASET.NAME = 'cifar10'
CFG.DATASET.NUM_LABELED = 250
CFG.DATASET.NUM_CLASSES = 10
CFG.DATASET.NUM_WORKERS = 1
CFG.DATASET.CONVERT_ONE_HOT = True
CFG.DATASET.IMG_SIZE = 32
CFG.DATASET.URATIO = 7
CFG.DATASET.TRAIN_BATCH_SIZE = 64
CFG.DATASET.TEST_BATCH_SIZE = 256
CFG.DATASET.CROP_RATIO = 0.875
CFG.DATASET.PIXEL_MEAN = [0.485, 0.456, 0.406]
CFG.DATASET.PIXEL_STD = [0.229, 0.224, 0.225]
CFG.DATASET.RANDAUG_N = 3
CFG.DATASET.RANDAUG_M = 5

CFG.MODEL = CN()
CFG.MODEL.NAME = 'wrn_28_2'
CFG.MODEL.PRETRAINED = False
CFG.MODEL.PRETRAINED_PATH = ''

CFG.OPTIMIZER = CN()
CFG.OPTIMIZER.NAME = 'SGD'
CFG.OPTIMIZER.LR = 0.03
CFG.OPTIMIZER.MOMENTUM = 0.9
CFG.OPTIMIZER.NESTEROV = True
CFG.OPTIMIZER.WEIGHT_DECAY = 0.0005
CFG.OPTIMIZER.SKIP_BN = True

CFG.TRAINER = CN()
CFG.TRAINER.SAT_EMA = 0.999
CFG.TRAINER.AMP_ENABLED = False
CFG.TRAINER.NUM_WARMUP_ITERS = 0
CFG.TRAINER.NUM_TRAIN_ITER = 1048576 # 2^20
CFG.TRAINER.NUM_EVAL_ITER = 5120
CFG.TRAINER.NUM_LOG_ITER = 512
CFG.TRAINER.USE_HARD_LABEL = True
CFG.TRAINER.EMA_VAL = 0.999
CFG.TRAINER.SOFT_TEMP = 0.5
CFG.TRAINER.ULB_LOSS_RATIO = 1.0
CFG.TRAINER.ENT_LOSS_RATIO = 0.1
