from yacs.config import CfgNode as CN

CFG = CN()

CFG.OUTPUT_DIR = ''
CFG.RESUME = ''
CFG.LOG_DIR = './logs'
CFG.USE_CUDA = True

CFG.USE_TB = True
CFG.PLOT_CURVES = True

CFG.DATASET = CN()
CFG.DATASET.PREPARE = False
CFG.DATASET.DIR = './data_download'
CFG.DATASET.NAME = 'cifar10'
CFG.DATASET.NUM_LABELED = 250
CFG.DATASET.NUM_CLASSES = 10
CFG.DATASET.NUM_WORKERS = 1
CFG.DATASET.CONVERT_ONE_HOT = True
CFG.DATASET.IMG_SIZE = 32
CFG.DATASET.URATIO = 7
CFG.DATASET.TRAIN_BATCH_SIZE = 64
CFG.DATASET.TEST_BATCH_SIZE = 256
CFG.DATASET.CROP_RATIO = 0.875
CFG.DATASET.PIXEL_MEAN = [0.485, 0.456, 0.406]
CFG.DATASET.PIXEL_STD = [0.229, 0.224, 0.225]
CFG.DATASET.RANDAUG_N = 3
CFG.DATASET.RANDAUG_M = 5

CFG.MODEL = CN()
CFG.MODEL.NAME = 'wrn_28_2'
CFG.MODEL.PRETRAINED = False
CFG.MODEL.PRETRAINED_PATH = ''

CFG.OPTIMIZER = CN()
CFG.OPTIMIZER.NAME = 'SGD'
CFG.OPTIMIZER.LR = 0.03
CFG.OPTIMIZER.MOMENTUM = 0.9
CFG.OPTIMIZER.NESTEROV = True
CFG.OPTIMIZER.WEIGHT_DECAY = 0.0005
CFG.OPTIMIZER.SKIP_BN = True

 
 